# Generated by Django 4.2 on 2023-04-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicle', models.CharField(blank=True, max_length=15, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('diametr', models.CharField(max_length=10)),
                ('complex', models.IntegerField(blank=True, max_length=3, null=True)),
                ('balance', models.IntegerField(blank=True, max_length=3, null=True)),
                ('count_gruz', models.IntegerField(blank=True, max_length=3, null=True)),
                ('sn', models.IntegerField(blank=True, max_length=3, null=True)),
                ('ust', models.IntegerField(blank=True, max_length=3, null=True)),
                ('mont', models.IntegerField(blank=True, max_length=3, null=True)),
                ('demont', models.IntegerField(blank=True, max_length=3, null=True)),
                ('tl', models.IntegerField(blank=True, max_length=10, null=True)),
                ('count_tl', models.IntegerField(blank=True, max_length=3, null=True)),
                ('appworks', models.CharField(blank=True, max_length=35, null=True)),
                ('count_appworks', models.IntegerField(blank=True, max_length=3, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
