# Generated by Django 4.2 on 2023-04-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0002_worktable_cost_appworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(default='04-04-2023'),
        ),
    ]
