# Generated by Django 4.2 on 2023-04-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0003_alter_worktable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(default='04-04-2023', editable=False),
        ),
    ]
