# Generated by Django 4.2 on 2023-04-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0009_alter_worktable_balance_alter_worktable_complex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='balance',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='complex',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='cost_appworks',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='count_gruz',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='demont',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='mont',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='sn',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='summ',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(default='2023-04-05 10:58', editable=False),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='ust',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
