# Generated by Django 4.2 on 2023-04-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0010_alter_worktable_balance_alter_worktable_complex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(default='2023-04-05 11:11', editable=False),
        ),
    ]
