# Generated by Django 4.2 on 2023-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0011_alter_worktable_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktable',
            name='count_appworks',
        ),
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(default='2023-04-05 11:50', editable=False),
        ),
    ]
