# Generated by Django 4.2 on 2023-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0012_remove_worktable_count_appworks_alter_worktable_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktable',
            name='count_tl',
        ),
        migrations.RemoveField(
            model_name='worktable',
            name='tl',
        ),
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(default='2023-04-05 12:06', editable=False),
        ),
    ]
