# Generated by Django 4.2 on 2023-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0014_alter_worktable_cost_appworks_alter_worktable_summ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
