# Generated by Django 4.2 on 2023-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0015_alter_worktable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
