# Generated by Django 4.2 on 2023-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0016_alter_worktable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='appworks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='vehicle',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
