# Generated by Django 4.2 on 2023-04-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0017_alter_worktable_appworks_alter_worktable_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='time',
            field=models.DateTimeField(blank=True, max_length=35, null=True),
        ),
    ]
