# Generated by Django 4.2 on 2023-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0019_alter_worktable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktable',
            name='times',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
