# Generated by Django 4.2 on 2023-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0020_worktable_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktable',
            name='prim',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
