# Generated by Django 4.1.3 on 2023-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinkassa', '0021_worktable_prim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='complex',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='count_gruz',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='demont',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='mont',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='sn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worktable',
            name='ust',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
